mysql:
  host: 127.0.0.1
  port: 3309
  username: crawler_user
  password: crawler_password
  database: account_track

targets:
  - id: 12
    table: twitter_jack
  - handle: nasa
    table: twitter_nasa
    workaround_status_id: 1677028218186997761
